# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4818f35e54c562cc3b637550c046e00217ae61e40084b15b192c955d1278b457ddf322ea526cbda838cd55cf0994f3ea5cd69882a2ed3a8952505bcb5676dc5f

test:
  secret_key_base: 4c1f166ce556718b14f62210a041dc2afdeefae9843aae41557bbbe8431fa7a7403a58400dca1a66d244a157f82e254b4d7e7f6b58c7f7614ee70f06fd8ec663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
